config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'weather#index'
  get 'weather/:country/:locality', to: 'weather#show'
  post 'weather/search', to: 'weather#search'
  get "*path", to: "application#catch_404", via: :all
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def catch_404
    flash[:error] = "Something bad happened"
    redirect_to root_path
  end
end

app/controllers/weather_controller.rb
class WeatherController < ApplicationController
  def index
    redirect_to controller: 'weather', action: 'show', country: 'germany', locality: 'berlin'
  end

  def show
    request = Weather::API.new(weather_params).get_weather
    if request.valid?
      @weather = request.data
    else
      flash[:error] = 'Location unknown'
      redirect_back(fallback_location: root_path)
    end
  end

  def search
    redirect_to controller: 'weather', action: 'show', country: weather_params[:country_short], locality: weather_params[:locality]
  end

  def weather_params
    params.permit(:country, :locality, :country_short)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/icon_for_weather_helper.rb
module IconForWeatherHelper
  ICON = {
    '01d' => 'wu-clear',
    '02d' => 'wu-partlysunny',
    '03d' => 'wu-cloudy',
    '04d' => 'wu-cloudy',
    '09d' => 'wu-rain',
    '10d' => 'wu-rain',
    '11d' => 'wu-tstorms',
    '13d' => 'wu-snow',
    '50d' => 'wu-fog'
  }
  DEFAULT_ICON = 'wu-unknown'
  CLASSES = ['wu', 'wu-white', 'wu-256']

  def icon_for(icon)
    icon_class = ICON.fetch(icon, DEFAULT_ICON)
    content_tag(:i, '', class: CLASSES + [icon_class])
  end
end

app/helpers/weather_helper.rb
module WeatherHelper
  def humidity_for(weather)
    content_tag(:li, %Q{ Humidity: #{weather.current.humidity} % })
  end

  def visibility_for(weather)
    content_tag(:li, %Q{ Visibility: #{weather.current.visibility} % })
  end

  def clouds_for(weather)
    content_tag(:li, %Q{ Clouds: #{weather.clouds} %})
  end

  def temperatures_for(weather)
    content_tag(:li, %Q{ Min. Temperature: #{weather.temperature.min} ºC }) +
    content_tag(:li, %Q{ Max. Temperature: #{weather.temperature.max} ºC })
  end

  def wind_for(weather)
    return '' if weather.wind.nil?
    content_tag(:li, %Q{ Wind speed: #{weather.wind.speed} m/s }) +
    content_tag(:li, %Q{ Wind degree: #{weather.wind.degree} º})
  end

  def snow_for(weather)
    return '' if weather.snow.nil?
    content.tag(:li, %Q{ Snow Volume: #{weather.snow.volume} })
  end

  def rain_for(weather)
    return '' if weather.rain.nil?
    content.tag(:li, %Q{ Rain Volume: #{weather.rain.volume} })
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lant="en">
  <head>
    <title>WeatherDemo</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "http://maps.googleapis.com/maps/api/js?key=#{ENV['GOOGLE_API_KEY']}&libraries=places" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': true %>
  </head>

  <body>
    <div class="site-wrapper">
      <div class="site-wrapper-inner">
        <div class="cover-container">
          <div class="inner cover">
            <%= render partial: 'shared/flash_errors'%>
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/shared/_flash_errors.html.erb
<div id="flash-errors">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key == "success" ? "success" : "danger"  %>">
      <%= value %>
    </div>
  <% end %>
</div>

app/views/weather/show.html.erb
<h1 class="cover-heading">
  Weather for: <%= @weather.location.full %>
</h1>

<div class="container">
  <div class="row">
    <div class="col col-lg-5">
      <div class="row">
        <div class="col">
          <p class="h2"><%= %Q(#{@weather.current.temperature} ºC) %></p>
          <%= @weather.current.name %>
          <%= icon_for @weather.current.icon %>
        </div>
        <div class="col">
        </div>
      </p>
      </div>
    </div>
    <div class="col col-sm-1">
    </div>
    <div class="float-right col col-lg-5">
      <ul class="list-unstyled">
      <%= humidity_for @weather %>
      <%= visibility_for @weather %>
      <%= clouds_for @weather %>
      <%= temperatures_for @weather %>
      <%= wind_for @weather %>
      </ul>
    </div>
  </div>
</div>
<%= form_tag weather_search_path, class: "form-inline", remote: true  do %>
  <input id="complete" class="form-control w-75" placeholder="Berlin, Germany" type="text">
  <input name="locality" hidden>
  <input name="country_short" hidden>
  <%= submit_tag 'Get weather', class: 'btn btn-secondary' %>
<% end %>